---
- name: Add Ubuntu repositories
  become: true
  # Use the builtin Ubuntu capability for adding universe, within which wireguard lives
  command: "add-apt-repository universe"
  register: adduniverserepo
  changed_when: "'already enabled' not in adduniverserepo.stdout"
  when: ansible_distribution == 'Ubuntu'
