---
- name: Add Ubuntu repositories
  # Use the builtin Ubuntu capability for adding universe, within which wireguard lives
  command: "add-apt-repository universe"
  register: adduniverserepo
  changed_when: "'already enabled' not in adduniverserepo.stdout"
  when: ansible_distribution == 'Ubuntu'

- name: Remove old PPA
  apt_repository:
    repo: 'ppa:wireguard/wireguard'
    state: absent

- name: Update APT repositories # only if they're old!
  apt:
    update_cache: yes
    cache_valid_time: 604800 # one week
